manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: nvhung9
      url-base: https://github.com/nvhung9
    - name: nguyendown
      url-base: https://github.com/nguyendown
  projects:
    - name: corne
      remote: nvhung9
      revision: main
      import: app/west.yml
  self:
    path: config
