manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: petejohanson
      url-base: https://github.com/petejohanson
    - name: nvhung9
      url-base: https://github.com/nvhung9

  projects:
    # - name: zmk
    #   remote: zmkfirmware
    #   revision: main
    #   import: app/west.yml

    - name: zmk
      remote: nvhung9
      revision: corne
      import: app/west.yml

  self:
    path: config
